POP_SIZE            = 100   # population size
MIN_DEPTH           = 0    # minimal initial random tree depth
MAX_INITIAL_DEPTH   = 4    # maximal initial random tree depth
MAX_DEPTH           = 17
INITIAL_NR_BINS     = 5  
TARGET              = 'DYN'
GENERATIONS         = 50  # maximal number of generations to run evolution
TOURNAMENT_SIZE     = 3    # size of tournament for tournament selection
XO_RATE             = 0.9  # crossover rate 
PROB_MUTATION       = 0.1  # per-node mutation probability
FITNESS             = 'RMSE'
MAX_ITER_NO_IMPROV  = 50