POP_SIZE            = 500   # population size
MIN_DEPTH           = 1    # minimal initial random tree depth
MAX_INITIAL_DEPTH   = 6    # maximal initial random tree depth
MAX_DEPTH           = 17
TARGET              = 'DYN'
BIN_WIDTH           = 1
GENERATIONS         = 50  # maximal number of generations to run evolution
TOURNAMENT_SIZE     = 10    # size of tournament for tournament selection
XO_RATE             = 0.9  # crossover rate 
PROB_MUTATION       = 0.1  # per-node mutation probability
FITNESS             = 'RMSE'