POP_SIZE                = 20   # population size
MIN_DEPTH               = 1    # minimal initial random tree depth
MAX_INITIAL_DEPTH       = 7    # maximal initial random tree depth
MAX_DEPTH               = 17
GENERATIONS             = 300  # maximal number of generations to run evolution
TOURNAMENT_SIZE         = 4    # size of tournament for tournament selection
XO_RATE                 = 0.9  # crossover rate 
PROB_MUTATION           = 0.1  # per-node mutation probability
DATASET_SPLITS          = 10
GENERATIONS_PER_SPLIT   = 5
FITNESS                 = 'RMSE'