POP_SIZE            = 100   # population size
MIN_DEPTH           = 0    # minimal initial random tree depth
MAX_INITIAL_DEPTH   = 6    # maximal initial random tree depth
MAX_DEPTH           = 17
BIN_WIDTH           = 0.2
TARGET              = 'DYN'
GENERATIONS         = 400  # maximal number of generations to run evolution
TOURNAMENT_SIZE     = 4   # size of tournament for tournament selection
XO_RATE             = 0.9  # crossover rate 
PROB_MUTATION       = 0.1  # per-node mutation probability
FITNESS             = 'RMSE'