POP_SIZE            = 50   # population size
MIN_DEPTH           = 0    # minimal initial random tree depth
MAX_INITIAL_DEPTH   = 6    # maximal initial random tree depth
MAX_DEPTH           = 17
INITIAL_NR_BINS     = 10 
MAX_COMPLEXITY      = 0.1
TARGET              = 'DYN'
GENERATIONS         = 300  # maximal number of generations to run evolution
TOURNAMENT_SIZE     = 4   # size of tournament for tournament selection
XO_RATE             = 0.9  # crossover rate 
PROB_MUTATION       = 0.1  # per-node mutation probability
FITNESS             = 'RMSE'
MAX_ITER_NO_IMPROV  = 30